mcm/json_layer/request.py

To continue on the workaround for slipping workflows with DQMIO dataset only.
https://hypernews.cern.ch/HyperNews/CMS/get/dataopsrequests/6495.html

skip workflows that only created a DQMIO

---

mcm/HTML/templates/request.manager.name.html
mcm/json_layer/request.py

Looks like able to get rid of the DQMIO ad-hoc check by selecting and ordering on expected tiers.
The status of a single output will help toggle a request to done : solving #742

Check on multiple output

---

mcm/rest_api/ChainedCampaignActions.py

Allow production managers to delete chained campaigns

---

mcm/rest_api/RequestActions.py

Wipe cmssw, sequences and keep output when cloning a request

---

mcm/ValidationControl.py
mcm/json_layer/request.py

Should fix this error happening when running validation from McM:
Unexpected exception while trying to submit HIG-RunIISummer19UL17wmLHEGEN-00182 message: string indices must be integers, not str
traceback Traceback (most recent call last):
File "/home/mcm/cmsPdmV/mcm/ValidationControl.py", line 342, in submit_jobs
result_dict = self.submit_request(prepid, test_path)
File "/home/mcm/cmsPdmV/mcm/ValidationControl.py", line 236, in submit_request
to_write = mcm_request.get_setup_file(run=True, do_valid=True, for_validation=True, gen_script=True)
File "/home/mcm/cmsPdmV/mcm/json_layer/request.py", line 1387, in get_setup_file
self.set_attribute('validation'['dqm'], 'RelVal' + self.get_attribute('dataset_name'))
TypeError: string indices must be integers, not str

Fixing error in GEN validation

---

mcm/scripts/edit_controller.js

The default limit of 20 is too small and often does not show all relevant chained campaigns. Bump it to 100.

Load up to 100 chained campaigns when creating a ticket

---

mcm/tools/communicator.py

Current SMTP server, smtp.cern.ch, is going to be decomissioned on June 30, 2023 Use the new server for sending emails from applications

[PDMVDEV-32] Change SMTP server

---

mcm/json_layer/request.py
mcm/main.py
mcm/rest_api/RequestActions.py
mcm/scripts/edit_controller.js
mcm/tools/communicator.py
mcm/tools/handlers.py

1. Load up to 100 chain campaigns when a ticket is created
2. Update singularity execution to load CA certificates from an auxiliary location. This update was applied in April 2023 after the CERN CA certificates issue.
3. Retrieve requests by the `dataset_name` attribute, this is related to #1100

Tickets, requests and singularity

---

mcm/json_layer/request.py

Solves: #1116
1. Allow the described role to modify the dataset name after the validation step.

Allow `generator contacts` to update the `dataset_name` attribute

---

mcm/scripts/edit.js
mcm/scripts/requests_ctrl.js

The cross sections shown in the McM UI were confusing users into thinking that they were correct, which is almost  never the case. Remove them from the UI (but keep them in the database for now).
@ggonzr could you deploy this to the dev machine for testing?

Remove cross sections from the UI

---

mcm/json_layer/generator_parameters.py

Related topic: https://cms-talk.web.cern.ch/t/problem-with-adding-cross-section-to-mcm-requests/36272/3

Remove `cross` option for generator parameters

---

mcm/rest_api/RequestActions.py

Requests without output are always considered either 0% or 100% complete by ReqMgr, there is no middle ground. For non-admins, force-completing a request is only possible if it is more than 50% complete. So if the request has no output, it can only be force-completed by a non-admin if it is already complete.
What the non-admins should do is trigger the force-completion of a request in the same (computing) workflow that does keep its output. Force-completion acts at the workflow level, and Unified is smart enough to mark all requests in the workflow as complete (100% completion for those not keeping output).
To help confused users trying to force-complete requests without output, add an error message telling them why it doesn't work and what they could do about it (try some other request …

Improve error message when force-completing a request with no output

---

mcm/json_layer/request.py

Related to: [#23](https://github.com/cms-PdmV/mcm_scripts/issues/23)
Use the new version for the McM REST client and avoid loading the old version from a folder in AFS. In this case, the module is loaded by the embedded script: [request_fragment_check.py](https://github.com/cms-sw/genproductions/blob/45b479075f09cdcb23fcc35c2142d80e360d8c99/bin/utils/request_fragment_check.py#L56-L63) owned by the CMS GEN team. To achieve a smooth integration with the new version, this sets an isolated `venv` where the McM REST client is installed and uses an isolated cms-sw singularity container to perform the execution using AlmaLinux 9 as OS and Python 3.9 as the default version.

Include the new McM REST client

---

mcm/json_layer/request.py

Fixes: https://github.com/cms-PdmV/cmsPdmV/issues/1147
Allow to set a status `done` for a request if its output datasets are valid with zero events only if the inspection is forced.

Send requests with valid datasets with zero events to status done

---

mcm/rest_api/RequestActions.py

The request body has been already cast as <cls: dict>. Remove the extra `json.loads()` instruction.

Avoid to cast the request body twice

---

mcm/json_layer/request.py

Fixes: https://github.com/cms-PdmV/cmsPdmV/issues/1162
Regarding inspection for submitted requests, skip the constraint about having all output datasets in `VALID` status if the inspection is forced.

Skip not valid restriction on forced inspection

---

mcm/json_layer/request.py

Fixes: https://github.com/cms-PdmV/cmsPdmV/issues/1168
Currently tags like `slc5:x86_64` or `slc5:amd64` do not exist anymore in `/cvmfs`, update them to use the new prefix `el5`.

Patch the `os_name` prefix for `slc5`

---

mcm/scripts/edit_controller.js
mcm/scripts/edit_many_controller.js

Fixes: https://github.com/cms-PdmV/cmsPdmV/issues/1171
This permission is already set in the `non_editable_request` configuration attribute stored in the `settings` database. Remove the label related to this attribute on the UI side.

Allow admins to update the `cmssw_release` in the edit form

---

mcm/json_layer/request.py

Allow this role to edit the `dataset_name` and the `process_string`.
This behavior was already authorized for `generator_conveners` and `generator_contacts` in #1117

Allow `production_managers` to edit more attributes for a request

---

mcm/automatic_scripts/validation/new_ssh_executor.py
mcm/optional-requirements.txt
mcm/tools/locator.py
mcm/tools/ssh_executor.py

Enable both `SSH` executors to authenticate to the remote host using Kerberos tickets via `gssapi-with-mic`.
Remember to install the optional packages `gssapi` and `pyasn1` to enable `paramiko` to use this authentication strategy.

Include support for `gssapi-with-mic` for authenticating SSH sessions

---

mcm/automatic_scripts/validation/validation_control.py
mcm/json_layer/request.py

Solves: https://github.com/cms-PdmV/cmsPdmV/issues/1181
For a given request prepid set in the `validation_skip_check` setting, skip if required some checks related to the `time_per_event`, `size_per_event` `memory` and `filter_efficiency`.

Skip dinamically some checks for the validation procedure

---

mcm/json_layer/request.py

Fixes: #1196 
The `memory` attribute will be overwritten/corrected on the submission phase with the validation results, so this check is not required. For more details, see:
- https://github.com/cms-PdmV/cmsPdmV/issues/1196

Remove constraint on memory for 1 core validation jobs

---

mcm/rest_api/ChainedRequestActions.py
mcm/tools/handlers.py

the current chain submission does not check on the validity of a chain during injection. this validity is set by action_parameter.flag set to True for active chain, and False for inactive ones

Check on action parameter flag during chain submission

---

mcm/json_layer/request.py

Solves: https://github.com/cms-PdmV/GrASP/issues/152
Always update this field if the Stats2 update is forced.

Update `output_dataset` for `done` requests

---

mcm/json_layer/request.py

the previous policy is able o select marginally better cpu efficiency over higher thread count. the new policy allows to select the max thread within a margin of the best cpu effiiciency for low filter efficiency requests.
requires new parameters
filter_eff_threshold_for_thread_choice = 0.001
filter_eff_margin_for_thread_choice = 0.05
and renaming one:
cpu_efficiency_threshold --> cpu_efficiency_threshold_for_thread_choice

Change thread count selection policy

---

mcm/rest_api/RequestActions.py
mcm/scripts/edit.js

Solves: https://github.com/cms-PdmV/cmsPdmV/issues/1017
Allow users to remove the generator parameters while updating a request. Make sure that at least one version of the parameters is provided.

Delete generator parameters for a request

---

mcm/HTML/invalidations.html
mcm/main.py
mcm/rest_api/InvalidationActions.py

This endpoint is not required anymore and it is currently dead code. It used to serve to the purpose to send the invalidation to the last stage without actually invalidating the dataset. For more details, see:
- https://github.com/cms-PdmV/cmsPdmV/issues/1163

Remove ClearInvalidations `/restapi/invalidations/clear`

---

mcm/json_layer/request.py

Fixes: https://github.com/cms-PdmV/cmsPdmV/issues/1214
While checking the request's fragment, accept paths referring to gridpacks stored at `/cvmfs/cms-griddata.cern.ch/phys_generator/gridpacks_tarball`

Include a new directory path for gridpacks

---

mcm/rest_api/DashboardActions.py
mcm/scripts/dashboard_controller.js

Do not allow users with the `user` role to consume this endpoint to mitigate a potential information disclosure about the application runtime environment and internals. Allow users with role `generator_contact` or higher to see the validation jobs and logs only for those with role `production_manager` or higher.

Decrease permissions for `Dashboard`

---

mcm/HTML/navbar_template.html

Completes: https://github.com/cms-PdmV/cmsPdmV/issues/1209
By default, when users click on this icon, display only the `started` campaigns

Query for started campaigns on the campaign tab

---

mcm/json_layer/request.py
mcm/tools/connection_wrapper.py

Fixes: https://github.com/cms-PdmV/cmsPdmV/issues/1223
If an HTTP response has a status code different from 200, return `False` instead of just bypassing the issue.

Change priority: Propagate errors from failed requests

---

mcm/json_layer/request.py

should be fixing #1157 so that dataset invalidation can stay in limbo for a while longer

only request invalidations are blocking

---

mcm/automatic_scripts/validation/validation_control.py
mcm/tools/locator.py

Completes: https://github.com/cms-PdmV/cmsPdmV/issues/1235
This PR modifies the validation failed message to include the expected parameters, the real measurements, and the number of threads used for an attempt in the first stage. Also, it allows moving files related to a failed validation attempt to `/eos` to inspection instead of just removing them

Show more details to users on failed validations
