mcm/json_layer/chained_request.py
mcm/json_layer/request.py
mcm/tools/handlers.py

DQM information in chain validation

---

mcm/json_layer/request.py

flowing a request after partial reset of a chain would not work because "completed_events" was not computed properly in get_stats resulting in stuck chains.

Get stats on multiple output

---

mcm/json_layer/request.py

Revert "Get stats on multiple output"

---

mcm/json_layer/chained_request.py
mcm/json_layer/request.py

Get stats on multiple output rebased

---

mcm/main.py
mcm/rest_api/InvalidationActions.py
mcm/rest_api/RestAPIMethod.py

this is a way to forget about the painful hand-shake on invalidations.
ops can then pull in and acknowledge the things to take to the bin.

Essential of acnkowledging invalidations

---

mcm/rest_api/ChainedRequestActions.py

With regards to a thread about "Submit FSPremix with taskchain"

Fix chained injection

---

mcm/rest_api/ChainedRequestActions.py

add prepid per task

---

mcm/HTML/mccms.html
mcm/json_layer/chained_request.py
mcm/json_layer/mccm.py
mcm/rest_api/ActionsActions.py
mcm/rest_api/ChainedRequestActions.py
mcm/rest_api/MccmActions.py
mcm/scripts/mccms_controller.js

import httplib
import os
import sys
import json
import time
host = os.environ.get('HOSTNAME')
conn = httplib.HTTPConnection("%s:5984" % (host))
conn.request("GET", "/mccms/_all_docs")
r1 = conn.getresponse()
data = json.loads(r1.read())['rows']
print('%s' % (data[0]))
doc_prepids = [el['id'] for el in data if el['id'].find('_') == -1]
print len(doc_prepids)
for prepid in doc_prepids:
print('.\n')
conn.request('GET', '/mccms/%s' % (prepid))
r2 = conn.getresponse()
deep_data = json.loads(r2.read())
if 'generated_chains' in deep_data:
generated_chains = deep_data['generated_chains']
if isinstance(generated_chains, dict):
print 'generated_chains already as dict: %s' % (generated_chains)
continue
elif isinstance(generated_chains, list):
chains_requests = {}
for chain in generated_chains: …

showing generated chains and requests in generated chains column in mccm

---

mcm/delete_notifications.py
mcm/notification_summary.py

Fix notification delete, replace tabs with spaces in notification summary

Notifications fix

---

mcm/HTML/campaigns.html
mcm/json_layer/campaign.py
mcm/main.py
mcm/rest_api/CampaignActions.py
mcm/scripts/campaigns_controller.js

Script to make all campaigns on_hold=0
```
import time
from couchdb_layer.mcm_database import database
db = database('campaigns')
page = 0
res = res = db.get_all(page, 20)
while len(res) != 0:
print('Current page: %d' % (page))
for doc in res:
doc['on_hold'] = 0
ret = db.save(doc)
if not ret:
print("Failed to save: %s" % (doc['_id']))
else:
print('Saved %s' % (doc['_id']))
page += 1
res = db.get_all(page, 20)
time.sleep(0.2)
```

Campaigns on hold

---

mcm/json_layer/request.py

Issue was solved two-three weeks ago

Do not update completed events if keep output is False

---

mcm/main.py

Add dummy ssh on McM start

---

mcm/scripts/flows_controller.js

Redirect to new flow after it's created

---

mcm/HTML/batches.html
mcm/HTML/campaigns.html
mcm/HTML/chained_campaigns.html
mcm/HTML/flows.html
mcm/HTML/lists.html
mcm/HTML/navbar_template.html
mcm/HTML/requests.html
mcm/HTML/settings.html
mcm/HTML/users.html
mcm/json_layer/chained_request.py
mcm/main.py
mcm/rest_api/ChainedRequestActions.py
mcm/rest_api/ListActions.py
mcm/scripts/css/mcm.css
mcm/scripts/lists_controller.js

List of non flowing chains

---

mcm/json_layer/request.py

Do not change priority if request manager name contains ACDC

---

mcm/rest_api/RequestActions.py

Remove tags on request clone

---

mcm/couchdb_layer/mcm_database.py
mcm/json_layer/chained_campaign.py
mcm/rest_api/ChainedRequestActions.py

Chained campaign chain type

---

mcm/HTML/edit.html
mcm/HTML/requests.html
mcm/json_layer/request.py

TODO after merge:
Add default value to existing requests.
Update unique index in database.

Transient output modules

---

mcm/HTML/chained_campaigns.html
mcm/HTML/edit.html
mcm/json_layer/chained_campaign.py
mcm/json_layer/chained_request.py
mcm/scripts/edit_controller.js

Add ability to disable CMSSW version check in chained campaigns

---

mcm/json_layer/request.py

Change minimum CPU efficiency threshold according to measured efficiency

---

mcm/json_layer/request.py

Exclude TransientOutputModule tiers from expected tiers

---

mcm/json_layer/request.py

Add sqrt to sigma calculation, show 8 digits after decimal point

---

mcm/rest_api/RequestActions.py

Add regex check for request dataset name

---

mcm/ValidationControl.py
mcm/json_layer/request.py
mcm/rest_api/RequestActions.py

Download only one file for GEN request checking script

---

mcm/json_layer/request.py
mcm/tools/handlers.py

Revert "Config generation on CC7"

---

mcm/json_layer/request.py
mcm/tools/handlers.py

Use singularity for slc7 scram arch config upload and request submissions

---

mcm/json_layer/request.py

Add GEN script checking only for pLHE, GS and wmLHEGS requests

---

mcm/scripts/edit.js

Add 5x and 6x validation multipliers

---

mcm/HTML/flows.html
mcm/main.py
mcm/rest_api/FlowActions.py
mcm/scripts/flows_controller.js

Add flow cloning

---

mcm/HTML/batches.html
mcm/HTML/templates/request.manager.name.html
mcm/json_layer/request.py
mcm/scripts/batches_controller.js
mcm/scripts/main_controller.js
mcm/scripts/requests_ctrl.js

Redo req mgr column

---

mcm/HTML/requests.html
mcm/json_layer/request.py
mcm/scripts/edit.js

Default set to False
Different options possible for the DQM event content 
Automatic upload into DQM GUI

GEN validation re-implemented in McM 

---

mcm/ValidationControl.py
mcm/json_layer/request.py

We will get soon from computing the request to check these parameters (memory and core efficiency) and for now they can be added in the get_test without any check.

More output on get_test for requests

---

mcm/ValidationControl.py
mcm/json_layer/request.py

small details to allow DQM upload

DQM validation fix

---

mcm/ValidationControl.py
mcm/json_layer/request.py
mcm/scripts/edit.js

Preliminary implementation of DQM GEN valiodation with references. Can be extended if it's correct with more samples.

Dqmvalidation

---

mcm/tools/communicator.py

Reverts cms-PdmV/cmsPdmV#1097. There was an issue the Python 2 and SMTP() client.

Revert "[PDMVDEV-32] Change SMTP server"

---

mcm/json_layer/request.py

Fixes: https://github.com/cms-PdmV/cmsPdmV/issues/1105

Download the McM request fragment outside `singularity`

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Add template for issues and bug reports

Add template for issues and bug reports

---

mcm/automatic_scripts/validation/validation_control.py
mcm/json_layer/request.py

Update validation HTCondor node to AlmaLinux9

---

mcm/json_layer/request.py

See [PDMVDEV-91](https://its.cern.ch/jira/browse/PDMVDEV-91)

Clarify the error message for requests using a lot of memory

---

mcm/tools/handlers.py

Use `singularity` containers for the injection script

---

mcm/json_layer/request.py

Solves: #1122
1. Remove the `default_scram_arch` attribute for the `get_setup_file2(...)` method

Remove dead code in request module

---

.github/workflows/test.yml
mcm/Dockerfile
mcm/couchdb_layer/mcm_database.py
mcm/deploy/.env.template
mcm/deploy/action.sh
mcm/deploy/couchdb-lucene.ini
mcm/deploy/mcm-databases.yml
mcm/package.json
mcm/tools/locator.py

1. Include an image definition for the McM application
In future iterations, a Docker compose script will be included to deploy a sample CouchDB database and a lucene search engine.

Build the application environment using containers

---

mcm/HTML/edit.html
mcm/HTML/edit_many.html

Increase the number of available extensions in the UI

---

.github/workflows/test.yml
.gitignore
mcm/.dockerignore
mcm/deploy/.env.template
mcm/deploy/action.sh
mcm/deploy/mcm-components.yml
mcm/json_layer/chained_request.py
mcm/json_layer/request.py
mcm/main.py
mcm/rest_api/DashboardActions.py
mcm/rest_api/RequestActions.py
mcm/tests/README.md
mcm/tests/api_tools.py
mcm/tests/base_test_tools.py
mcm/tests/campaign/static/campaign.json
mcm/tests/campaign/test_campaign.py
mcm/tests/requirements.txt
mcm/tests/test_api_tools.py
mcm/tools/handlers.py
mcm/tools/locator.py

This solves the elements 1, 2, and 3 related to: #1124
Summary (details on each commit message):
1. Build and deploy the McM application based on the branch's code.
2. Configure a minimum sample dataset to run the application. 
3. Include some helper modules for coding the test cases and include constraints on the minimum test cases required.
4. Include a test suite to check the Campaign API.
5. Update the GitHub Action workflow to execute the test suite.

Test environment and first test cases

---

mcm/couchdb_layer/mcm_database.py
mcm/rest_api/ControlActions.py

Reverts cms-PdmV/cmsPdmV#1142
Some sections raise exceptions that are not fully handled by other endpoints, making the application fail on ticket operations or search queries.

Revert "Limit infinite requests"

---

mcm/rest_api/ListActions.py

Fixes: #1154
Check that primary id fields: `_id`, `prepid`, and `_rev` are provided in the request body, and that `prepid` and `_id` is the same. Check also that the list to be updated already exists!

Include more checks for the `UpdateList` endpoint

---

mcm/json_layer/request.py
mcm/tools/handlers.py

Fixes for: https://github.com/cms-PdmV/cmsPdmV/issues/1160 on the web application side.
Refactors the injection command to be executed in `cms-sw` containers providing newer Python versions and dependencies. Also runs the upload step in two phases, one for generating the configuration tweaks and the other for submitting the configuration to the ReqMgr2 config cache.

Updates for the request upload and injection steps.

---

mcm/json_layer/request.py

Fixes: https://github.com/cms-PdmV/cmsPdmV/issues/1158
Attempt to pick the total number of events for a dataset following the schema used by PREP2. Instead of returning a `None` value for `get_events_for_dataset`, raise an exception.

Attempt to pick events for old migrated requests

---

mcm/json_layer/request.py

Fixes: #1175 
On validation of pileup requests, pick files from DBS from a specific site.

Validation: Pick pileup files from a specific site

---

mcm/json_layer/request.py

with a view to submitting a taskchain that contains two output modules with the same event content, we can use https://github.com/cms-sw/cmssw/pull/47501 and set `--eventcontent MINIAODSIM1` and the conversion to stepchain should be able to succeed.

fuzzy event content

---

mcm/json_layer/request.py

Fixes: https://github.com/cms-PdmV/cmsPdmV/issues/1165
Reset this field on other related requests using as `input_dataset` the `output_dataset` values to be invalidated.

Reset `input_dataset` field on request reset

---

mcm/json_layer/request.py

Completes: https://github.com/cms-PdmV/cmsPdmV/issues/1183
To avoid keeping a huge list of requests on this setting, remove the entry when a request is on `done` status. Also, include an entry in the history to record every time the request has bypassed the validation procedure.

Remove done requests from `validation_bypass`

---

mcm/json_layer/request.py

Download the mentioned script via the `cms-gen/genproductions_scripts` repository.

Download `request_fragment_check.py` from CERN GitLab

---

mcm/automatic_scripts/validation/validation_control.py
mcm/json_layer/request.py
mcm/json_layer/validation.py
mcm/rest_api/DashboardActions.py
mcm/tools/settings.py

Completes: https://github.com/cms-PdmV/cmsPdmV/issues/1177
This includes a new validation strategy to run validation jobs based on the output number of events. It also refactors the validation process and allows to dynamically select between validation strategies for a request via database settings. Also, this includes some updates to change dynamically the HTCondor pool and the accounting group for the validation job configuration.

Include a new validation strategy

---

mcm/rest_api/RequestActions.py

the list of generator parameters cannot be smaller than 1 if there was already a list of generator parameters

update on generator parameters

---

mcm/HTML/mccms.html
mcm/scripts/mccms_controller.js

link to mccm gitlab issues

---

mcm/json_layer/request.py
mcm/json_layer/validation.py

Fixes: https://github.com/cms-PdmV/cmsPdmV/issues/1222
Fix issues running the gen script for validations starting on a thread configuration different from 1-thread.

Fix: Generation script and initial thread validation

---

mcm/automatic_scripts/validation/validation_control.py

Related to: https://github.com/cms-PdmV/cmsPdmV/pull/1237
When a validation succeeds, remove any record stored in the `/eos` related to previous failed attempts.

Remove failed validation records when validation succeeds
